repos:
  # Pre-commit hooks for basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      - id: end-of-file-fixer
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      - id: check-yaml
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      - id: check-toml
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      - id: check-json
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      - id: check-added-large-files
      - id: check-merge-conflict
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      - id: debug-statements
        exclude: '^src/span_panel_api/generated_client/.*|generate_client\.py|tests/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'

  # Ruff for formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      # Run formatter first
      - id: ruff-format
        exclude: '^src/span_panel_api/generated_client/.*|generate_client\.py|scripts/coverage\.py|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'
      # Then linter
      - id: ruff-check
        args: ['--fix']
        exclude: '^src/span_panel_api/generated_client/.*|generate_client\.py|scripts/coverage\.py|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'

  # Black limited to handling end-of-file newlines and blank lines
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [
          '--line-length=125',
          '--skip-string-normalization',
          '--skip-magic-trailing-comma',
          '--target-version=py312',
          '--extend-exclude=src/span_panel_api/generated_client|generate_client\.py|scripts/coverage\.py|\.venv|venv'
        ]
        exclude: '^src/span_panel_api/generated_client/.*|generate_client\.py|scripts/coverage\.py|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*'

  # Markdownlint for markdown files
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.15.0
    hooks:
      - id: markdownlint-cli2
        args: ['--config', '.markdownlint.json']
        exclude: '^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*|\.venv/.*|node_modules/.*|htmlcov/.*'

  # MyPy for type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        additional_dependencies:
          - httpx
          - attrs
          - python-dateutil
          - click
          - typing-extensions
          - pytest
        args: ['--config-file=pyproject.toml']
        exclude: '^src/span_panel_api/generated_client/.*|tests/.*|docs/.*|\..*_cache/.*|dist/.*|venv/.*'

  # Check for common security issues
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']
        exclude: '^tests/.*|^src/span_panel_api/generated_client/.*|\..*_cache/.*|dist/.*|venv/.*'

  # Poetry check for pyproject.toml validation
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check
      # poetry-lock hook removed to prevent CI failures due to file modifications
      # Lock file should be manually updated when dependencies change

  # Quick coverage check (total only, no details)
  - repo: local
    hooks:
      - id: pytest-cov-summary
        name: coverage summary
        entry: bash
        language: system
        args: ['-c', 'output=$(poetry run pytest tests/ --cov=src/span_panel_api --cov-config=pyproject.toml -q 2>&1); if echo "$output" | grep -q "FAILED"; then echo "$output"; exit 1; else echo "$output" | grep -E "(passed|TOTAL)" | tr "\n" " " | sed "s/=*//g"; echo; fi']
        pass_filenames: false
        always_run: true
        verbose: true
