"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from span_panel_api.models.branch import Branch


class TestBranch(unittest.TestCase):
    """Branch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Branch:
        """Test Branch
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Branch`
        """
        model = Branch()
        if include_optional:
            return Branch(
                id = 56,
                relay_state = 'UNKNOWN',
                instant_power_w = 1.337,
                imported_active_energy_wh = 1.337,
                exported_active_energy_wh = 1.337,
                measure_start_ts_ms = 56,
                measure_duration_ms = 56,
                is_measure_valid = True
            )
        else:
            return Branch(
                id = 56,
                relay_state = 'UNKNOWN',
                instant_power_w = 1.337,
                imported_active_energy_wh = 1.337,
                exported_active_energy_wh = 1.337,
                measure_start_ts_ms = 56,
                measure_duration_ms = 56,
                is_measure_valid = True,
        )
        """

    def testBranch(self):
        """Test Branch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
