"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from span_panel_api.models.nice_to_have_threshold import NiceToHaveThreshold


class TestNiceToHaveThreshold(unittest.TestCase):
    """NiceToHaveThreshold unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NiceToHaveThreshold:
        """Test NiceToHaveThreshold
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `NiceToHaveThreshold`
        """
        model = NiceToHaveThreshold()
        if include_optional:
            return NiceToHaveThreshold(
                nice_to_have_threshold_low_soe = span_panel_api.models.state_of_energy.StateOfEnergy(
                    percentage = 56, ),
                nice_to_have_threshold_high_soe = span_panel_api.models.state_of_energy.StateOfEnergy(
                    percentage = 56, )
            )
        else:
            return NiceToHaveThreshold(
        )
        """

    def testNiceToHaveThreshold(self):
        """Test NiceToHaveThreshold"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
