"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from span_panel_api.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_delete_client_api_v1_auth_clients_name_delete(self) -> None:
        """Test case for delete_client_api_v1_auth_clients_name_delete

        Delete Client
        """
        pass

    def test_deprecated_spaces_endpoint_stub_api_v1_spaces_get(self) -> None:
        """Test case for deprecated_spaces_endpoint_stub_api_v1_spaces_get

        Deprecated Spaces Endpoint Stub
        """
        pass

    def test_deprecated_spaces_endpoint_stub_api_v1_spaces_spaces_id_get(self) -> None:
        """Test case for deprecated_spaces_endpoint_stub_api_v1_spaces_spaces_id_get

        Deprecated Spaces Endpoint Stub
        """
        pass

    def test_deprecated_spaces_endpoint_stub_api_v1_spaces_spaces_id_post(self) -> None:
        """Test case for deprecated_spaces_endpoint_stub_api_v1_spaces_spaces_id_post

        Deprecated Spaces Endpoint Stub
        """
        pass

    def test_generate_jwt_api_v1_auth_register_post(self) -> None:
        """Test case for generate_jwt_api_v1_auth_register_post

        Generate Jwt
        """
        pass

    def test_get_all_clients_api_v1_auth_clients_get(self) -> None:
        """Test case for get_all_clients_api_v1_auth_clients_get

        Get All Clients
        """
        pass

    def test_get_circuit_state_api_v1_circuits_circuit_id_get(self) -> None:
        """Test case for get_circuit_state_api_v1_circuits_circuit_id_get

        Get Circuit State
        """
        pass

    def test_get_circuits_api_v1_circuits_get(self) -> None:
        """Test case for get_circuits_api_v1_circuits_get

        Get Circuits
        """
        pass

    def test_get_client_api_v1_auth_clients_name_get(self) -> None:
        """Test case for get_client_api_v1_auth_clients_name_get

        Get Client
        """
        pass

    def test_get_islanding_state_api_v1_islanding_state_get(self) -> None:
        """Test case for get_islanding_state_api_v1_islanding_state_get

        Get Islanding State
        """
        pass

    def test_get_main_relay_state_api_v1_panel_grid_get(self) -> None:
        """Test case for get_main_relay_state_api_v1_panel_grid_get

        Get Main Relay State
        """
        pass

    def test_get_panel_meter_api_v1_panel_meter_get(self) -> None:
        """Test case for get_panel_meter_api_v1_panel_meter_get

        Get Panel Meter
        """
        pass

    def test_get_panel_power_api_v1_panel_power_get(self) -> None:
        """Test case for get_panel_power_api_v1_panel_power_get

        Get Panel Power
        """
        pass

    def test_get_panel_state_api_v1_panel_get(self) -> None:
        """Test case for get_panel_state_api_v1_panel_get

        Get Panel State
        """
        pass

    def test_get_storage_nice_to_have_threshold_api_v1_storage_nice_to_have_thresh_get(
        self,
    ) -> None:
        """Test case for get_storage_nice_to_have_threshold_api_v1_storage_nice_to_have_thresh_get

        Get Storage Nice To Have Threshold
        """
        pass

    def test_get_storage_soe_api_v1_storage_soe_get(self) -> None:
        """Test case for get_storage_soe_api_v1_storage_soe_get

        Get Storage Soe
        """
        pass

    def test_get_wifi_scan_api_v1_wifi_scan_get(self) -> None:
        """Test case for get_wifi_scan_api_v1_wifi_scan_get

        Get Wifi Scan
        """
        pass

    def test_run_panel_emergency_reconnect_api_v1_panel_emergency_reconnect_post(
        self,
    ) -> None:
        """Test case for run_panel_emergency_reconnect_api_v1_panel_emergency_reconnect_post

        Run Panel Emergency Reconnect
        """
        pass

    def test_run_wifi_connect_api_v1_wifi_connect_post(self) -> None:
        """Test case for run_wifi_connect_api_v1_wifi_connect_post

        Run Wifi Connect
        """
        pass

    def test_set_circuit_state_api_v1_circuits_circuit_id_post(self) -> None:
        """Test case for set_circuit_state_api_v1_circuits_circuit_id_post

        Set Circuit State
        """
        pass

    def test_set_main_relay_state_api_v1_panel_grid_post(self) -> None:
        """Test case for set_main_relay_state_api_v1_panel_grid_post

        Set Main Relay State
        """
        pass

    def test_set_storage_nice_to_have_threshold_api_v1_storage_nice_to_have_thresh_post(
        self,
    ) -> None:
        """Test case for set_storage_nice_to_have_threshold_api_v1_storage_nice_to_have_thresh_post

        Set Storage Nice To Have Threshold
        """
        pass

    def test_set_storage_soe_api_v1_storage_soe_post(self) -> None:
        """Test case for set_storage_soe_api_v1_storage_soe_post

        Set Storage Soe
        """
        pass

    def test_system_status_api_v1_status_get(self) -> None:
        """Test case for system_status_api_v1_status_get

        System Status
        """
        pass


if __name__ == "__main__":
    unittest.main()
