"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from span_panel_api.models.panel_meter import PanelMeter


class TestPanelMeter(unittest.TestCase):
    """PanelMeter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PanelMeter:
        """Test PanelMeter
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PanelMeter`
        """
        model = PanelMeter()
        if include_optional:
            return PanelMeter(
                main_meter = span_panel_api.models.main_meter_energy.MainMeterEnergy(
                    produced_energy_wh = 1.337,
                    consumed_energy_wh = 1.337, ),
                feedthrough = span_panel_api.models.feedthrough_energy.FeedthroughEnergy(
                    produced_energy_wh = 1.337,
                    consumed_energy_wh = 1.337, )
            )
        else:
            return PanelMeter(
                main_meter = span_panel_api.models.main_meter_energy.MainMeterEnergy(
                    produced_energy_wh = 1.337,
                    consumed_energy_wh = 1.337, ),
                feedthrough = span_panel_api.models.feedthrough_energy.FeedthroughEnergy(
                    produced_energy_wh = 1.337,
                    consumed_energy_wh = 1.337, ),
        )
        """

    def testPanelMeter(self):
        """Test PanelMeter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
