"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from span_panel_api.models.status_out import StatusOut


class TestStatusOut(unittest.TestCase):
    """StatusOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusOut:
        """Test StatusOut
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `StatusOut`
        """
        model = StatusOut()
        if include_optional:
            return StatusOut(
                software = span_panel_api.models.software_status.SoftwareStatus(
                    firmware_version = '',
                    update_status = '',
                    env = '', ),
                system = span_panel_api.models.system_status.SystemStatus(
                    manufacturer = '',
                    serial = '',
                    model = '',
                    door_state = 'UNKNOWN',
                    proximity_proven = True,
                    uptime = 56, ),
                network = span_panel_api.models.network_status.NetworkStatus(
                    eth0_link = True,
                    wlan_link = True,
                    wwan_link = True, )
            )
        else:
            return StatusOut(
                software = span_panel_api.models.software_status.SoftwareStatus(
                    firmware_version = '',
                    update_status = '',
                    env = '', ),
                system = span_panel_api.models.system_status.SystemStatus(
                    manufacturer = '',
                    serial = '',
                    model = '',
                    door_state = 'UNKNOWN',
                    proximity_proven = True,
                    uptime = 56, ),
                network = span_panel_api.models.network_status.NetworkStatus(
                    eth0_link = True,
                    wlan_link = True,
                    wwan_link = True, ),
        )
        """

    def testStatusOut(self):
        """Test StatusOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
