"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from span_panel_api.models.boolean_in import BooleanIn


class TestBooleanIn(unittest.TestCase):
    """BooleanIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BooleanIn:
        """Test BooleanIn
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BooleanIn`
        """
        model = BooleanIn()
        if include_optional:
            return BooleanIn(
                value = True
            )
        else:
            return BooleanIn(
                value = True,
        )
        """

    def testBooleanIn(self):
        """Test BooleanIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
