"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestPriority(unittest.TestCase):
    """Priority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriority(self):
        """Test Priority"""
        # inst = Priority()


if __name__ == "__main__":
    unittest.main()
