"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from span_panel_api_client.models.allowed_endpoint_groups import AllowedEndpointGroups


class Client(BaseModel):
    """
    Client
    """  # noqa: E501

    description: StrictStr | None = None
    issued_at: StrictInt | None = None
    allowed_endpoint_groups: AllowedEndpointGroups
    __properties: ClassVar[list[str]] = [
        "description",
        "issued_at",
        "allowed_endpoint_groups",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Client from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of allowed_endpoint_groups
        if self.allowed_endpoint_groups:
            _dict["allowed_endpoint_groups"] = self.allowed_endpoint_groups.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Client from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "description": obj.get("description"),
                "issued_at": obj.get("issued_at"),
                "allowed_endpoint_groups": (
                    AllowedEndpointGroups.from_dict(obj["allowed_endpoint_groups"])
                    if obj.get("allowed_endpoint_groups") is not None
                    else None
                ),
            }
        )
        return _obj
