"""
Span

Span Panel REST API

The version of the OpenAPI document: v1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field
from span_panel_api_client.models.feedthrough_energy import FeedthroughEnergy
from span_panel_api_client.models.main_meter_energy import MainMeterEnergy


class PanelMeter(BaseModel):
    """
    PanelMeter
    """  # noqa: E501

    main_meter: MainMeterEnergy = Field(alias="mainMeter")
    feedthrough: FeedthroughEnergy
    __properties: ClassVar[list[str]] = ["mainMeter", "feedthrough"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PanelMeter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of main_meter
        if self.main_meter:
            _dict["mainMeter"] = self.main_meter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of feedthrough
        if self.feedthrough:
            _dict["feedthrough"] = self.feedthrough.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PanelMeter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "mainMeter": (
                    MainMeterEnergy.from_dict(obj["mainMeter"])
                    if obj.get("mainMeter") is not None
                    else None
                ),
                "feedthrough": (
                    FeedthroughEnergy.from_dict(obj["feedthrough"])
                    if obj.get("feedthrough") is not None
                    else None
                ),
            }
        )
        return _obj
