# Battery Test Configuration
# Used for testing battery behavior with bidirectional energy flow

panel_config:
  serial_number: "BATTERY-TEST-001"
  total_tabs: 8
  main_size: 100

circuit_templates:
  basic_battery:
    energy_profile:
      mode: "bidirectional"
      power_range: [-5000.0, 5000.0]
      typical_power: 0.0
      power_variation: 0.1
    relay_behavior: "controllable"
    priority: "NON_ESSENTIAL"
    battery_behavior:
      enabled: true
      max_charge_power: -5000
      max_discharge_power: 5000
      charge_hours: [10, 11, 12]
      discharge_hours: [18, 19, 20]
      idle_hours: [2, 3, 4]
      idle_power_range: [-50.0, 50.0]
      demand_factors:
        "18": 0.8
        "19": 0.9
        "20": 0.7
      solar_intensities:
        "10": 0.8
        "11": 0.9
        "12": 0.7

  simple_consumer:
    energy_profile:
      mode: "consumer"
      power_range: [10.0, 100.0]
      typical_power: 50.0
      power_variation: 0.1
    relay_behavior: "controllable"
    priority: "NON_ESSENTIAL"

circuits:
  - id: "battery_circuit"
    name: "Battery Circuit"
    template: "basic_battery"
    tabs: [1, 3]  # L1 + L2 = Valid 240V

  - id: "load_circuit"
    name: "Load Circuit"
    template: "simple_consumer"
    tabs: [2, 4]  # L1 + L2 = Valid 240V

# Circuit synchronization for 240V battery system
tab_synchronizations:
  - tabs: [1, 3]  # Battery circuit 240V split phase
    behavior: "240v_split_phase"
    power_split: "equal"
    energy_sync: true
    template: "battery_sync"

unmapped_tabs: [5, 6]

simulation_params:
  update_interval: 1
  time_acceleration: 1.0
  noise_factor: 0.05
  enable_realistic_behaviors: true
