# Configuration for testing realistic behavior patterns
# Demonstrates cycling, time-of-day, and smart behaviors

panel_config:
  serial_number: "SPAN-BEHAVIOR-001"
  total_tabs: 12
  main_size: 200

circuit_templates:
  cycling_hvac:
    power_range: [0.0, 3500.0]
    energy_behavior: "consume_only"
    typical_power: 2800.0
    power_variation: 0.1
    relay_behavior: "controllable"
    priority: "NON_ESSENTIAL"
    cycling_pattern:
      on_duration: 900    # 15 minutes on
      off_duration: 1800  # 30 minutes off

  time_of_day_lighting:
    power_range: [0.0, 100.0]
    energy_behavior: "consume_only"
    typical_power: 40.0
    power_variation: 0.2
    relay_behavior: "controllable"
    priority: "MUST_HAVE"
    time_of_day_profile:
      enabled: true
      peak_hours: [18, 19, 20, 21, 22]

  smart_ev_charger:
    power_range: [0.0, 7200.0]
    energy_behavior: "consume_only"
    typical_power: 6000.0
    power_variation: 0.05
    relay_behavior: "controllable"
    priority: "NON_ESSENTIAL"
    smart_behavior:
      max_power_reduction: 0.6  # Can reduce to 40% during grid stress

  variable_solar:
    power_range: [-8000.0, 0.0]
    energy_behavior: "produce_only"
    typical_power: -4000.0
    power_variation: 0.3
    relay_behavior: "non_controllable"
    priority: "MUST_HAVE"
    time_of_day_profile:
      enabled: true
      peak_hours: [10, 11, 12, 13, 14]  # Solar peak production

circuits:
  - id: "main_hvac_cycling"
    name: "Main HVAC with Cycling"
    template: "cycling_hvac"
    tabs: [1, 2]

  - id: "outdoor_lights_tod"
    name: "Outdoor Lights (Time of Day)"
    template: "time_of_day_lighting"
    tabs: [3, 4]

  - id: "ev_charger_smart"
    name: "EV Charger (Smart)"
    template: "smart_ev_charger"
    tabs: [5, 6]

  - id: "solar_array_variable"
    name: "Solar Array (Variable)"
    template: "variable_solar"
    tabs: [7, 8]

  - id: "backup_hvac_cycling"
    name: "Backup HVAC with Cycling"
    template: "cycling_hvac"
    tabs: [9, 10]

unmapped_tabs: [11, 12]

simulation_params:
  update_interval: 3
  time_acceleration: 1.0
  noise_factor: 0.05
  enable_realistic_behaviors: true
