# Producer Test Configuration
# Used for testing producer energy profiles (solar, generators, etc.)

panel_config:
  serial_number: "PRODUCER-TEST-001"
  total_tabs: 8
  main_size: 100

circuit_templates:
  solar_producer:
    energy_profile:
      mode: "producer"
      power_range: [-2000.0, 0.0]
      typical_power: -1000.0
      power_variation: 0.3
    relay_behavior: "controllable"
    priority: "ESSENTIAL"
    time_of_day_profile:
      enabled: true

  generator_producer:
    energy_profile:
      mode: "producer"
      power_range: [-5000.0, 0.0]
      typical_power: -3000.0
      power_variation: 0.1
    relay_behavior: "controllable"
    priority: "ESSENTIAL"

  basic_consumer:
    energy_profile:
      mode: "consumer"
      power_range: [0.0, 1000.0]
      typical_power: 500.0
      power_variation: 0.1
    relay_behavior: "controllable"
    priority: "NON_ESSENTIAL"

  battery:
    energy_profile:
      mode: "bidirectional"
      power_range: [-3000.0, 3000.0]
      typical_power: 0.0
      power_variation: 0.1
    relay_behavior: "non_controllable"
    priority: "MUST_HAVE"
    battery_behavior:
      enabled: true
      charge_hours: [10, 11, 12, 13, 14, 15]  # Charge during solar production
      discharge_hours: [18, 19, 20, 21]  # Discharge during peak demand
      idle_hours: [22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 16, 17]
      max_charge_power: -2500.0
      max_discharge_power: 2000.0
      idle_power_range: [-50.0, 50.0]

circuits:
  - id: "solar_array"
    name: "Solar Array"
    template: "solar_producer"
    tabs: [1, 3]  # L1 + L2 = Valid 240V

  - id: "backup_generator"
    name: "Backup Generator"
    template: "generator_producer"
    tabs: [2, 4]  # L1 + L2 = Valid 240V

  - id: "house_load"
    name: "House Load"
    template: "basic_consumer"
    tabs: [5, 7]  # L1 + L2 = Valid 240V

  - id: "battery_storage"
    name: "Battery Storage"
    template: "battery"
    tabs: [6, 8]  # L1 + L2 = Valid 240V

# Circuit synchronizations for 240V systems
tab_synchronizations:
  - tabs: [1, 3]  # Solar array 240V split phase
    behavior: "240v_split_phase"
    power_split: "equal"
    energy_sync: true
    template: "solar_sync"

  - tabs: [2, 4]  # Generator 240V split phase
    behavior: "240v_split_phase"
    power_split: "equal"
    energy_sync: true
    template: "generator_sync"

  - tabs: [6, 8]  # Battery storage 240V split phase
    behavior: "240v_split_phase"
    power_split: "equal"
    energy_sync: true
    template: "battery_sync"

unmapped_tabs: []  # All tabs now used

simulation_params:
  update_interval: 1
  time_acceleration: 1.0
  noise_factor: 0.05
  enable_realistic_behaviors: true
