# Validation Test Configuration
# Used for testing YAML validation logic and basic functionality

panel_config:
  serial_number: "VALIDATION-TEST-001"
  total_tabs: 8
  main_size: 100

circuit_templates:
  basic_consumer:
    energy_profile:
      mode: "consumer"
      power_range: [0.0, 1000.0]
      typical_power: 500.0
      power_variation: 0.1
    relay_behavior: "controllable"
    priority: "NON_ESSENTIAL"

  high_power_consumer:
    energy_profile:
      mode: "consumer"
      power_range: [100.0, 5000.0]
      typical_power: 2500.0
      power_variation: 0.2
    relay_behavior: "controllable"
    priority: "ESSENTIAL"

circuits:
  - id: "test_circuit_1"
    name: "Test Circuit 1"
    template: "basic_consumer"
    tabs: [1, 3]  # L1 + L2 = Valid 240V

  - id: "test_circuit_2"
    name: "Test Circuit 2"
    template: "high_power_consumer"
    tabs: [2, 4]  # L1 + L2 = Valid 240V

unmapped_tabs: [5, 6]

simulation_params:
  update_interval: 1
  time_acceleration: 1.0
  noise_factor: 0.05
  enable_realistic_behaviors: true
