"""Constants for the SPAN Panel API client."""

# SPAN Panel State Constants
# DSM (Demand Side Management) States
DSM_GRID_UP = "DSM_GRID_UP"
DSM_GRID_DOWN = "DSM_GRID_DOWN"
DSM_ON_GRID = "DSM_ON_GRID"
DSM_OFF_GRID = "DSM_OFF_GRID"

# Panel Run Configuration States
PANEL_ON_GRID = "PANEL_ON_GRID"
PANEL_OFF_GRID = "PANEL_OFF_GRID"
PANEL_BACKUP = "PANEL_BACKUP"

# Main Relay States
MAIN_RELAY_OPEN = "OPEN"
MAIN_RELAY_CLOSED = "CLOSED"
MAIN_RELAY_UNKNOWN = "UNKNOWN"
