"""Has a producer moved past the pin?

`spec_lock.json` records three producers this repository copies from or is
generated by: the eBus **specification**, whose capability catalogs are vendored
under `packages/schema-1/spec/`; **panelbench**, whose captures are byte-copied
into that same directory; and the **eBus emitter**, a released distribution that
produced the reference tree twenty test modules replay. Any of them can move
without a file here being touched, and when one does the pin stops describing a
producer and starts describing a moment.

The provenance tests answer the other half of the question — do our bytes still
match the commit we claim they came from — and they answer it against sibling
checkouts, which says nothing about what a producer has *published* since. This
asks the producers themselves, over the network and with no checkout at all:
PyPI for the emitter's latest release, GitHub's compare API for what panelbench
changed, `git ls-remote` for where a branch is.

It is a script rather than a workflow step because it runs in two places.
`.github/workflows/peer-drift.yml` runs it daily under `--strict`, which is the
backstop. `.pre-commit-config.yaml` runs it on every commit, which is where it is
meant to catch things: the drift this exists to prevent was a producer release
that nobody here noticed until a scheduled job went red, and a check only CI runs
is a check that finds out late.

**A verdict, or context.** Two comparisons are verdicts, and both are verdicts
about bytes in this repository having gone stale:

- the emitter's *release*, because the reference tree is a capture of one and
  `capture_parent_child_reference.py` refuses to write a capture from any other
  version. Commits on the emitter's branch are unreleased work, reported because
  they are what a release will be made of, never a call to action.
- a panelbench commit that touches a file we vendor. Commits that touch nothing
  we copy are reported and stay green: a README commit there is not a defect
  here.

The specification is context only and never a verdict. It says what a device
class *may* publish, the vendored catalogs are byte-compared against
`synced_commit` by `ci.yml`, and a specification that has moved is something to
read rather than something to fix.

**Not having asked is not the same fact as there being nothing new.** A producer
that could not be reached is reported as UNKNOWN, loudly, and exits 0 — a laptop
on a plane still has to be able to commit. `--strict` turns unknown into a
failure, because in CI there is no such excuse.

Nothing here restates a pin, a path or a repository. Every one of them is read
from `spec_lock.json`, which is their single home; a constant in this file would
be a second one, agreeing right up until the day somebody moved only one.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
import argparse
import json
import os
import pathlib
import subprocess
import sys
from typing import Literal, Protocol, TextIO
import urllib.error
import urllib.parse
import urllib.request

_REPO = pathlib.Path(__file__).resolve().parent.parent
# Run as a file (`python scripts/peer_drift.py`) the interpreter puts *this*
# directory on the path, not the repository, so the sibling module holding the
# lockfile reader is not importable as `scripts._lock` until we say where the
# repository is. Imported as `scripts.peer_drift`, which is how the tests read
# it, the entry is already there and this is a no-op.
if str(_REPO) not in sys.path:
    sys.path.append(str(_REPO))

from scripts._lock import LOCK, REPO, load, mapping, required, string  # noqa: E402
from scripts._lock import peer as pinned_peer  # noqa: E402

PANELBENCH = "panelbench"
"""The SPAN-side publisher this parser is developed against, and the one whose
captures are byte-copied into this repository."""

PANEL_SIM = "ebus-panel-sim"
"""The eBus specification's own executable publisher, and the producer of the
reference tree. A released distribution, which is why its release is the
verdict."""

SPECIFICATION = "specification"
"""Not a peer in `spec_lock.json` — it is the document both peers implement, and
it is pinned at the top level as `spec_repo` / `synced_commit`."""

TIMEOUT = 10.0
"""Seconds per network call. Short deliberately: this runs in a pre-commit hook,
and a producer that has not answered in ten seconds is a producer we will report
as unknown rather than one worth waiting for."""

COMPARE_FILE_LIMIT = 300
"""GitHub's compare API lists at most this many changed files. A comparison that
hits the limit cannot be read as "nothing we vendor changed", because the file
that did may be the one the API declined to name — so it is reported as unknown,
not as current."""

EBUS_SPEC_FILE = ".ebus-spec.json"
"""The producer's own record of which specification commit it implements.
Not vendored, but read by `test_the_peer_record_matches_the_simulator_lockfile`,
so a change to it is a change to something this repository depends on."""

VENDORED = {
    "tree": "packages/schema-1/spec/fixtures/simulator_tree.json",
    "wire": "packages/schema-1/spec/fixtures/simulator_wire.json",
}
"""Where each panelbench capture is copied *to*. The paths it is copied *from*
are the pin's own (`peers.panelbench.fixtures`) and are read from the lockfile;
these are paths inside this repository, which that peer's block deliberately does
not record — see `spec_lock.json`'s note on why `fixtures` and `produces` are two
keys rather than one."""

GITHUB_API = "https://api.github.com"
PYPI_JSON = "https://pypi.org/pypi"

Verdict = Literal["current", "drift", "unknown"]


class Unreachable(Exception):
    """A producer could not be asked.

    Deliberately not an answer. Every caller turns this into `unknown` and says
    so in the summary, because the alternative — treating silence as agreement —
    is how a check reports green on the day it had nothing to report at all.
    """


class HttpGet(Protocol):
    """Fetch a URL, or raise `Unreachable`. Injected so tests never leave the machine."""

    def __call__(self, url: str) -> str: ...


class LsRemote(Protocol):
    """Resolve a ref in a remote repository to a commit, or raise `Unreachable`."""

    def __call__(self, repo: str, ref: str) -> str: ...


@dataclass(frozen=True)
class Producer:
    """One producer, asked and answered.

    `pinned` and `observed` are the same fact as `detail`, in the currency the
    comparison was made in — a release for the emitter, a commit for the other
    two. The prose is what a person reads in a job summary; these are what a test
    can assert on without matching sentences.
    """

    name: str
    pinned: str
    observed: str
    verdict: Verdict
    detail: str
    advisory: bool = False
    """Reported, never counted. Set for the specification, whose movement is
    context for reading a disagreement rather than a reason to change anything
    here, and so must not fail a commit or a job."""

    def section(self) -> str:
        return f"## {self.name}\n\n{self.detail.rstrip()}\n"


@dataclass(frozen=True)
class Comparison:
    """GitHub's answer to `compare/<base>...<head>`, narrowed to what we read.

    `behind_by` rather than the API's own `status` word: what we need to know is
    whether the pin is an ancestor of the branch, and a non-zero count of commits
    the base has and the head does not is exactly that question answered.
    """

    ahead_by: int
    behind_by: int
    files: tuple[str, ...]

    @property
    def capped(self) -> bool:
        return len(self.files) >= COMPARE_FILE_LIMIT


# ---------------------------------------------------------------------------
# Asking, over the network
# ---------------------------------------------------------------------------


def _headers(url: str) -> dict[str, str]:
    """Authenticate to the GitHub API when a token is around, and nowhere else.

    CI has one and wants the higher rate limit; a developer machine usually does
    not, and 60 unauthenticated requests an hour is ample for a hook that makes
    at most one such request per commit. The host check is not decoration: a
    credential sent to a service that did not ask for it is a credential
    disclosed, and PyPI has no use for a GitHub token.
    """
    if not url.startswith(GITHUB_API):
        return {}
    headers = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN") or ""
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def http_get(url: str) -> str:
    request = urllib.request.Request(url, headers=_headers(url))
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT) as response:  # noqa: S310
            body: bytes = response.read()
    except urllib.error.HTTPError as error:
        if error.code in (403, 429) and error.headers.get("x-ratelimit-remaining") == "0":
            raise Unreachable(
                "GitHub's rate limit is spent; set GH_TOKEN to raise it from the unauthenticated 60/hr"
            ) from error
        raise Unreachable(f"HTTP {error.code} {error.reason}") from error
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        raise Unreachable(str(error)) from error
    return body.decode("utf-8", errors="replace")


def ls_remote(repo: str, ref: str) -> str:
    """The commit a remote ref names, without cloning anything.

    `GIT_TERMINAL_PROMPT=0` because this runs in a pre-commit hook: a repository
    that has gone private must report as unreachable rather than stop a commit at
    a password prompt nobody is watching for.
    """
    environment = dict(os.environ, GIT_TERMINAL_PROMPT="0")
    try:
        completed = subprocess.run(  # noqa: S603
            ["git", "ls-remote", repo, ref],
            capture_output=True,
            text=True,
            timeout=TIMEOUT,
            check=False,
            env=environment,
        )
    except subprocess.TimeoutExpired as error:
        raise Unreachable(f"git ls-remote did not answer within {TIMEOUT:.0f}s") from error
    except OSError as error:
        raise Unreachable(str(error)) from error
    if completed.returncode != 0:
        detail = completed.stderr.strip().splitlines()
        raise Unreachable(detail[-1] if detail else f"git ls-remote exited {completed.returncode}")
    fields = completed.stdout.split()
    if not fields:
        raise Unreachable(f"{repo} has no {ref}")
    return fields[0]


# ---------------------------------------------------------------------------
# Reading what came back, which is somebody else's JSON
# ---------------------------------------------------------------------------


def _answer(body: str, who: str) -> dict[str, object]:
    try:
        loaded: object = json.loads(body)
    except json.JSONDecodeError as error:
        raise Unreachable(f"{who} did not answer with JSON ({error})") from error
    if not isinstance(loaded, Mapping):
        raise Unreachable(f"{who} answered with {type(loaded).__name__}, not an object")
    return {str(key): value for key, value in loaded.items()}


def _member(source: Mapping[str, object], key: str, who: str) -> dict[str, object]:
    value = source.get(key)
    if not isinstance(value, Mapping):
        raise Unreachable(f"{who} answered with no {key!r} object")
    return {str(inner): item for inner, item in value.items()}


def _field(source: Mapping[str, object], key: str, who: str) -> str:
    value = source.get(key)
    if not isinstance(value, str):
        raise Unreachable(f"{who} answered with no {key!r} string")
    return value


def _count(source: Mapping[str, object], key: str, who: str) -> int:
    value = source.get(key)
    if isinstance(value, bool) or not isinstance(value, int):
        raise Unreachable(f"{who} answered with no {key!r} count")
    return value


def _filenames(source: Mapping[str, object], who: str) -> tuple[str, ...]:
    """The changed files, which the API omits entirely when there are none."""
    listed = source.get("files", [])
    if not isinstance(listed, Sequence) or isinstance(listed, str | bytes):
        raise Unreachable(f"{who} answered with a 'files' that is not a list")
    names: list[str] = []
    for entry in listed:
        if not isinstance(entry, Mapping):
            raise Unreachable(f"{who} answered with a file entry that is not an object")
        names.append(_field({str(key): value for key, value in entry.items()}, "filename", who))
    return tuple(names)


# ---------------------------------------------------------------------------
# Comparing, which is pure
# ---------------------------------------------------------------------------


def slug(url: str) -> str:
    """owner/name, which is what the GitHub API addresses a repository by."""
    return url.removeprefix("https://github.com/").removesuffix(".git")


def short(commit: str) -> str:
    return commit[:12]


def fixtures(peer: Mapping[str, object]) -> dict[str, str]:
    """The captures byte-copied out of panelbench, by kind, as the pin names them.

    Paths *inside panelbench*: `spec_lock.json` records this peer's artifacts
    under `fixtures` for exactly that reason, and the other peer's under
    `produces`, whose paths are inside this repository.
    """
    listed = mapping(required(peer, "fixtures", f"peers.{PANELBENCH}"), f"peers.{PANELBENCH}.fixtures")
    return {str(kind): str(path) for kind, path in listed.items()}


def watched(peer: Mapping[str, object]) -> tuple[str, ...]:
    """The files in panelbench whose movement is our problem.

    The captures we byte-copy, named by the pin, plus the producer's own record
    of the specification commit it implements. Everything else in that repository
    may change freely.
    """
    return tuple(sorted(fixtures(peer).values())) + (EBUS_SPEC_FILE,)


def touched(changed: Sequence[str], watch: Sequence[str]) -> tuple[str, ...]:
    """Those of `watch` the producer changed, in the order `watch` names them."""
    changes = set(changed)
    return tuple(path for path in watch if path in changes)


def released_tag(peer: Mapping[str, object], version: str) -> str:
    """`version` spelled the way that producer tags a release.

    Derived from the pinned pair rather than assumed: the lockfile records both
    `tag` and `version`, so whatever prefix the producer puts on one is readable
    from the other.
    """
    tag = string(peer, "tag", f"peers.{PANEL_SIM}")
    pinned = string(peer, "version", f"peers.{PANEL_SIM}")
    return f"{tag.removesuffix(pinned)}{version}" if tag.endswith(pinned) else version


def unasked(lock: Mapping[str, object]) -> tuple[str, ...]:
    """Producers the lockfile pins that this script has no way to ask about.

    A new peer added to `spec_lock.json` and not here would be silently exempt
    from the only check that notices it moving, which is the failure this whole
    script exists to prevent, one level up.
    """
    peers = mapping(required(lock, "peers", LOCK.name), "peers")
    return tuple(sorted(set(peers) - set(BUILDERS)))


def unvendored(lock: Mapping[str, object]) -> tuple[str, ...]:
    """Capture kinds the pin names that this script knows no destination for.

    `VENDORED` is the one thing here that is not read from the lockfile, because
    the destinations are paths in this repository and that peer's block records
    only its sources. A kind in one and not the other would still be *detected*
    as drift — `watched` reads the pin — but the summary would go quiet about
    where to copy it, which is the half a reader actually acts on.
    """
    return tuple(sorted(set(fixtures(pinned_peer(PANELBENCH, lock))) - set(VENDORED)))


def _unknown(who: str, error: Exception) -> str:
    return (
        f"**UNKNOWN — could not ask {who}:** `{error}`\n\n"
        "Not having asked is not the same fact as there being nothing new, so this is "
        "reported rather than passed over. It does not fail a commit; `--strict`, which "
        "CI passes, makes it fail there, where being unable to reach a producer is a "
        "problem with the run rather than with the network in a coffee shop."
    )


# ---------------------------------------------------------------------------
# The producers, one shape each
# ---------------------------------------------------------------------------


def emitter(lock: Mapping[str, object], get: HttpGet, ls: LsRemote) -> Producer:
    """The released distribution the reference tree was captured from.

    The release is the verdict and the branch is context, because the capture
    script gates on a release: it refuses to write a tree taken from any version
    other than the pinned one, so unreleased commits cannot produce a capture we
    would accept even if we wanted one.
    """
    peer = pinned_peer(PANEL_SIM, lock)
    distribution = string(peer, "distribution", f"peers.{PANEL_SIM}")
    pinned = string(peer, "version", f"peers.{PANEL_SIM}")
    context = _emitter_commits(peer, ls)
    who = f"PyPI for {distribution}"

    try:
        body = get(f"{PYPI_JSON}/{urllib.parse.quote(distribution)}/json")
        latest = _field(_member(_answer(body, who), "info", who), "version", who)
    except Unreachable as error:
        return Producer(PANEL_SIM, pinned, "", "unknown", f"{_unknown(who, error)}\n\n{context}")

    if latest == pinned:
        detail = f"Latest release is `{latest}`, which is what we pin. The reference tree is current."
        return Producer(PANEL_SIM, pinned, latest, "current", f"{detail}\n\n{context}")

    capture = string(peer, "capture_script", f"peers.{PANEL_SIM}")
    produces = mapping(required(peer, "produces", f"peers.{PANEL_SIM}"), f"peers.{PANEL_SIM}.produces")
    tree = str(required(produces, "tree", f"peers.{PANEL_SIM}.produces"))
    detail = (
        f"Latest release is `{latest}`, we pin `{pinned}`.\n\n"
        "The reference tree was captured from the pinned release, so it now describes a\n"
        "producer that has been superseded. To follow:\n\n"
        "```bash\n"
        f"# in a checkout of the emitter at {released_tag(peer, latest)}, from its own environment\n"
        f"uv run python ../{REPO.name}/{capture} \\\n"
        f"  ../{REPO.name}/{tree}\n"
        "```\n\n"
        f"The script refuses until `peers.{PANEL_SIM}.version` and `.commit` in\n"
        f"`{LOCK.name}` name the release you captured from, which is what keeps the\n"
        "bytes and the claim about them from drifting apart. Read the emitter's CHANGELOG\n"
        "for the wire changes before accepting the new capture: a diff confined to each\n"
        "`$description`'s `version` means nothing moved."
    )
    return Producer(PANEL_SIM, pinned, latest, "drift", f"{detail}\n\n{context}")


def _emitter_commits(peer: Mapping[str, object], ls: LsRemote) -> str:
    """Where the emitter's branch is, which is context and says so."""
    repo = string(peer, "repo", f"peers.{PANEL_SIM}")
    ref = string(peer, "ref", f"peers.{PANEL_SIM}")
    commit = string(peer, "commit", f"peers.{PANEL_SIM}")
    heading = f"### {slug(repo)} commits"
    try:
        head = ls(repo, f"refs/heads/{ref}")
    except Unreachable as error:
        return f"{heading}\n\nCould not ask where `{ref}` is (`{error}`)."
    if head == commit:
        return f"{heading}\n\n`{ref}` is at `{short(commit)}`, the commit we pin."
    return (
        f"{heading}\n\n"
        f"`{ref}` is at `{short(head)}`, we pin `{short(commit)}` — the branch head has\n"
        "moved past the pin. Unreleased work, so not itself a reason to recapture; the\n"
        "release comparison above is. How many commits, and which, needs a clone — the\n"
        "scheduled `peer-drift.yml` run has one and lists them."
    )


def panelbench(lock: Mapping[str, object], get: HttpGet, ls: LsRemote) -> Producer:
    """The repository whose captures are byte-copied here.

    Two questions, cheapest first. `git ls-remote` says whether the branch has
    moved at all, and on the ordinary day — the pin at the branch head — that is
    the whole answer and no API request is made. Only a branch that has moved is
    worth spending a compare on, and only then does *what* it changed matter.
    """
    peer = pinned_peer(PANELBENCH, lock)
    repo = string(peer, "repo", f"peers.{PANELBENCH}")
    ref = string(peer, "ref", f"peers.{PANELBENCH}")
    commit = string(peer, "commit", f"peers.{PANELBENCH}")
    name = slug(repo)
    watch = watched(peer)

    try:
        head = ls(repo, f"refs/heads/{ref}")
    except Unreachable as error:
        return Producer(PANELBENCH, commit, "", "unknown", _unknown(f"{name} where `{ref}` is", error))
    if head == commit:
        return Producer(
            PANELBENCH,
            commit,
            head,
            "current",
            f"`{ref}` is at `{short(commit)}`, the commit we pin. Nothing to re-vendor.",
        )

    who = f"GitHub what {name} changed"
    try:
        comparison = compare(repo, commit, ref, get)
    except Unreachable as error:
        return Producer(PANELBENCH, commit, head, "unknown", _unknown(who, error))

    moved = f"`{ref}` is at `{short(head)}`, we pin `{short(commit)}`"
    if comparison.behind_by:
        detail = (
            f"**UNKNOWN — {moved}, and the pin is not an ancestor of it.**\n\n"
            "The pin names a commit this branch does not contain — a branch that was\n"
            f"rebased, squash-merged or deleted. `peers.{PANELBENCH}.ref` in `{LOCK.name}`\n"
            "needs to name a ref the pinned commit is actually on, and until it does\n"
            "nothing here can say whether what we vendor is current."
        )
        return Producer(PANELBENCH, commit, head, "unknown", detail)

    changed = touched(comparison.files, watch)
    if not changed and comparison.capped:
        # Asked in this order because a file we vendor appearing in a truncated
        # list is still a file we vendor having changed. Only the *absence* of one
        # is unsafe to conclude from a list the API cut short.
        detail = (
            f"**UNKNOWN — {moved}, {comparison.ahead_by} commits ahead, and the comparison\n"
            f"named {COMPARE_FILE_LIMIT} changed files, which is all the API will list.**\n\n"
            'A truncated list cannot be read as "nothing we vendor changed", because the\n'
            "file that did may be one it declined to name. Compare against a checkout — the\n"
            "byte comparison in `tests/test_schema_one_conformance.py` is the answer that\n"
            "does not truncate."
        )
        return Producer(PANELBENCH, commit, head, "unknown", detail)

    if not changed:
        detail = (
            f"{moved} — {comparison.ahead_by} commits ahead, nothing we copy changed.\n\n"
            "Green deliberately: this repository vendors two captures and reads one\n"
            "lockfile out of that branch, and a commit touching none of them is the\n"
            "producer's business rather than ours."
        )
        return Producer(PANELBENCH, commit, head, "current", detail)

    return Producer(PANELBENCH, commit, head, "drift", _panelbench_drift(moved, comparison, changed, fixtures(peer)))


def _panelbench_drift(
    moved: str, comparison: Comparison, changed: Sequence[str], sources: Mapping[str, str]
) -> str:
    """What to do about a producer that changed something we keep a copy of."""
    lines = [
        f"**{moved} — {comparison.ahead_by} commits ahead, and it changed what we vendor:**",
        "",
        *(f"- `{path}`" for path in changed),
        "",
    ]
    captures = sorted((source, VENDORED[kind]) for kind, source in sources.items() if source in changed)
    if captures:
        lines += [
            "Re-vendor and re-pin together, in one change:",
            "",
            "```bash",
            *(f"cp $PANELBENCH_DIR/{source} \\\n   {destination}" for source, destination in captures),
            "```",
            "",
            f"then set `peers.{PANELBENCH}.commit` in `{LOCK.relative_to(REPO)}` to the",
            "commit you copied from. A capture without a commit bump records where the bytes",
            "came from as a guess.",
            "",
        ]
    if EBUS_SPEC_FILE in changed:
        lines += [
            f"`{EBUS_SPEC_FILE}` is the producer's own record of the specification commit it",
            f"implements. The two sides are reading different vocabularies until `peers.{PANELBENCH}`'s",
            "`synced_commit` and the vendored catalogs move together.",
            "",
        ]
    lines += [
        "The byte comparison in `tests/test_schema_one_conformance.py` is what settles it,",
        "and it is the same one `ci.yml` runs — this only says the producer moved first.",
    ]
    return "\n".join(lines)


def compare(repo: str, base: str, head: str, get: HttpGet) -> Comparison:
    """`base...head`, as GitHub answers it, needing no clone of either."""
    name = slug(repo)
    who = f"GitHub what {name} changed"
    url = f"{GITHUB_API}/repos/{name}/compare/{urllib.parse.quote(base)}...{urllib.parse.quote(head)}"
    answer = _answer(get(url), who)
    return Comparison(
        ahead_by=_count(answer, "ahead_by", who),
        behind_by=_count(answer, "behind_by", who),
        files=_filenames(answer, who),
    )


def specification(lock: Mapping[str, object], ls: LsRemote) -> Producer:
    """The document both producers implement. Context, never a verdict.

    A specification that has moved does not make anything here wrong: it says
    what a device class *may* publish, and what this repository vendors out of it
    is byte-compared against `synced_commit` by `ci.yml`. Reported so that a
    disagreement with a producer can be read against the right revision of the
    document, and marked advisory so it can never fail a commit.
    """
    repo = string(lock, "spec_repo", LOCK.name)
    pinned = string(lock, "synced_commit", LOCK.name)
    name = slug(repo)
    try:
        head = ls(repo, "HEAD")
    except Unreachable as error:
        return Producer(SPECIFICATION, pinned, "", "unknown", _unknown(f"{name} where HEAD is", error), advisory=True)
    if head == pinned:
        return Producer(
            SPECIFICATION,
            pinned,
            head,
            "current",
            f"`{name}` is at `{short(head)}`, the commit we sync to.",
            advisory=True,
        )
    detail = (
        f"`{name}` is at `{short(head)}`, we sync to `{short(pinned)}`.\n\n"
        "Context, not a verdict, and it fails nothing. The specification says what a device\n"
        "class may publish rather than what one does, and the catalogs vendored from it are\n"
        "byte-compared against the pinned commit by `ci.yml`. Worth reading when a producer\n"
        "and this parser disagree — the two sides may be reading different revisions of it."
    )
    return Producer(SPECIFICATION, pinned, head, "drift", detail, advisory=True)


BUILDERS: dict[str, Callable[[Mapping[str, object], HttpGet, LsRemote], Producer]] = {
    PANELBENCH: panelbench,
    PANEL_SIM: emitter,
    SPECIFICATION: lambda lock, get, ls: specification(lock, ls),
}
"""One builder per producer, because they are not the same shape. Keyed by the
name the lockfile uses, so `--peer` names what `spec_lock.json` names."""


# ---------------------------------------------------------------------------
# Saying it
# ---------------------------------------------------------------------------


def render(found: Sequence[Producer]) -> str:
    return "\n".join(producer.section() for producer in found)


def exit_code(found: Sequence[Producer], *, strict: bool) -> int:
    """1 when a producer we depend on has moved past its pin, 0 when none has.

    Unknown is 0 unless `--strict`: a network this script could not reach is not
    evidence about a producer, and a commit is not the place to insist on one.
    Advisory producers count for neither — see `Producer.advisory`.
    """
    decisive = [producer for producer in found if not producer.advisory]
    if any(producer.verdict == "drift" for producer in decisive):
        return 1
    if strict and any(producer.verdict == "unknown" for producer in decisive):
        return 1
    return 0


def main(
    argv: Sequence[str] | None = None,
    *,
    get: HttpGet = http_get,
    ls: LsRemote = ls_remote,
    out: TextIO | None = None,
) -> int:
    parser = argparse.ArgumentParser(
        prog="peer_drift.py",
        description="Ask each producer pinned in spec_lock.json whether it has moved past the pin.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="fail when a producer could not be asked, not only when one has drifted (CI passes this)",
    )
    parser.add_argument(
        "--peer",
        choices=sorted(BUILDERS),
        help="ask one producer instead of all of them",
    )
    namespace = parser.parse_args(argv)
    strict = bool(namespace.strict)
    only = None if namespace.peer is None else str(namespace.peer)

    lock = load()
    missing = unasked(lock)
    if missing:
        raise SystemExit(
            f"{LOCK.name} pins {', '.join(missing)}, which this script has no way to ask. "
            "Add a builder to scripts/peer_drift.py: a producer nobody asks about is a "
            "producer that moves unnoticed, which is the whole thing this check exists to stop."
        )
    unplaced = unvendored(lock)
    if unplaced:
        raise SystemExit(
            f"peers.{PANELBENCH}.fixtures names a {', '.join(unplaced)} capture and "
            "scripts/peer_drift.py records no path in this repository it is copied to. "
            "Add it to VENDORED, or a drift report will name the file and not what to do about it."
        )

    asked = [name for name in (PANELBENCH, PANEL_SIM, SPECIFICATION) if only is None or name == only]
    found = [BUILDERS[name](lock, get, ls) for name in asked]
    print(render(found), end="", file=sys.stdout if out is None else out)
    return exit_code(found, strict=strict)


if __name__ == "__main__":
    raise SystemExit(main())
